<Project Sdk="Microsoft.NET.Sdk.Razor">
  <PropertyGroup>
    <TargetFrameworks>net10.0</TargetFrameworks>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Allegiance.Blazor.Highcharts" />
    <PackageReference Include="Blazored.LocalStorage" />
    <PackageReference Include="BlazorGoogleMaps" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" />
    <PackageReference Include="MudBlazor" />
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="Tomlyn" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\capnproto-dotnetcore\Capnp.Net.Runtime\Capnp.Net.Runtime.csproj" />
    <ProjectReference Include="..\mas_capnproto_schemas\gen\csharp\zalfmas_capnpschemas.csproj" />
    <ProjectReference Include="..\mas_csharp_common\common.csproj" />
  </ItemGroup>
</Project>
